### PR TITLE
Add styling to timeline page / Users pages / Friendship page

### PR DESCRIPTION
**Pull request by DcRonan**
### Friendshipv2

1. Friendship creates 2 rows
2. Unit and Integrations tests

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @DcRonan and @khalilhamdii 
### You have done really well so far :clap: However you have an issue to fix:-
- [x] You have a failing unit test, see the image below
test-fail
### Make the change and submit for another code review. Good luck.
- Happy coding!

**Comment by khalilhamdii** [comment]
@rOluochKe Thank you for your review! We did fix the issue.

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! Well done implementing the functional requirements for this milestone. However, there are a few things to improve in order to finish this milestone. These include:
- [x] Your test suite is very limited e.g. the only tested model I see is the `friendship` model. Try to add more tests. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Make sure linting is properly configured the linter checks are running.
- [x] __[Optional]__ Read about `n+1` and make sure there are no `n + 1` queries in index views [Recommended article](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5).

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by rOluochKe — APPROVED** [review]
Hello Team
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
